# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: CogSciPrag homepage
description: Homepage of the CSP lab at the University of Tübingen.
baseurl: "/home"
url: "https://cogsciprag.github.io"
og_image: /assets/img/profile-pic.jpg
google_analytics: "UA-121636368-3"

theme: bay_jekyll_theme

header:
  pages:
    - name: Home
      slug: /
    - name: Research
    - name: People
    - name: Publications
    - name: Resources

footer:
  show_powered_by: true
  contact:
    - type: email
      name: Email
      value: yourmail@domain.com
  follow:
    - type: github
      name: GitHub
      link: https://github.com/CogSciPrag

# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed
  - jekyll-scholar
# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1

scholar:
  sort_by: "descending"
  order: "descending"
  group_by: "year"
  group_order: "descending"
